name: umayr
favicon: null
layout_spectrum: 0.8275701974052936
typography_spectrum: 0.29034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#8da8bf'
    - '#445f74'
    - '#44293e'
    - '#f8f8f8'
  brandStrength: 0.8125
  lightness: 0.02610739879310131
  saturation: 0.8937675328925252
  rhythmicContrast: 0.04007045621983707
purpose: []
